### ISSUE TITLE
Meta: Test scenarios

### ISSUE THREAD

**Issue by jbcrail** [Azure/azure-data-lake-store-python#78]
**Cancel upload/download**
- [ ] Validate that the final file does not exist
- [ ] Resume the upload/download
- [ ] Validate that it completes successfully

**Validate retry logic when a basic REST call fails for uploader/downloader**
- [x] Mock a failure in append/create. Validate the operation retries and eventually fails
- [ ] Resume the upload/download with mocked failure remove, verify it succeeds

**Verify overwrite logic**
- [x] Files/folders should not be overwritten if the user does not indicate a force operation
- [x] Files/folders should be overwritten if the user does indicate force (default should not be force)

**Verify record boundary splitting is honored**
- [x] If this is passed in, verify that it is honored.
- [x] Verify that if the user passes in this boundary splitting and the data is >4MB when a boundary is found, that we throw (since we cannot support records that are longer than 4mb).

**Progress tracking/state validation**
- [x] Validate that metadata about the upload/download is correct upon completion/error termination
- [x] This should also be done during the resume tests to ensure the metadata is accurate/useable.

**Comment by martindurant** [comment]
"Verify that if the user passes in this boundary splitting and the data is >4MB when a boundary is found, that we throw (since we cannot support records that are longer than 4mb)." -> should not be an exception - we instead write a delimited block < 4MB, and then another block with the rest.  
The only problem would be if there is no delimiter at all within > 4MB of data; in this case the block must be written as-is, perhaps with a warning, but I suggest no exception.

**Comment by rrenfrow86** [comment]
@jbcrail - do you have updates to this issue?

**Comment by jbcrail** [comment]
@rrenfrow86 I checked off those cases in which we've already addressed them or will soon address them via a pending PR.

**Comment by begoldsm** [comment]
@jbcrail and @martindurant if the user requests a delimited block, and there are no delimiters at all within a 4mb chunk you **must** throw. Appending the data with a warning is dangerous here, as the user may not ever see the warning and, down the road in the system, their data will be corrupt when running jobs, which will result in failures much later in the pipeline. That in turn will result in an escalation to our service engineers to investigate why their data doesn't have the boundaries they thought it had.
In this case, if the call has bad data that they want delimited, it is best to fail immediately, and force them to make a decision:
1. fix their data to have valid delimiters where no record is > 4MB
2. Change their delimiter to satisfy the record limit
3. Upload their data without delimiters, which forces the user to explicitly acknowledge that their data will not be delimited on the server.

**Comment by martindurant** [comment]
OK; the appropriate place is
```
                    if place < 0:
                        # not found - write whole block
                        limit = self.blocksize
```
@jbcrail or I will change this to an exception (ValueError) with a summary of your words above, and sneak this into one of the PRs.

**Comment by akharit** [comment]
Closing this as it is based on old code base and I think we have the correct test coverage.
